version: '3'

services:

  gt-keycloak:
    image: quay.io/keycloak/keycloak:10.0.2
    container_name: ingresso-projeto-keycloak
    volumes: 
        - ./keycloak/realm-export.json:/keycloak/realm-export.json
    ports:
      - 8084:8080
    environment:
      KEYCLOAK_IMPORT: /keycloak/realm-export.json
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: h2


  organizacional-api:
    build:
      context: ./organizacional-api
      dockerfile: Dockerfile
    container_name: organizacional-api
    ports: 
      - "8085:8080"

  ingresso-projeto-postgres:
    build:
      context: ./ingresso-database
      dockerfile: Dockerfile
    container_name: ingresso-projeto-postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=ingresso
      - POSTGRES_DB=ingresso
      - POSTGRES_USER=ingresso

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
